import "unknwn.idl" ;
[
    object,
    uuid(BAC91261-3C2F-4CFB-9AFB-F823572F838F),
    helpstring("IMyMath Interface"),
    pointer_default(unique),
    dual,
    oleautomation
]
interface IMyMath : IDispatch
{
    import "oaidl.idl" ;
    HRESULT SumOfTwoIntegers([in]int, [in]int, [out,retval]int *);
    HRESULT SubtractionOfTwoIntegers([in]int, [in]int, [out,retval]int *);
};
[
    uuid(FE3BC724-3D4B-44A3-B512-0DB23FB5BDA0),
    version(1.0),
    helpstring("My Automation Component's Type Library")
]
library AutomationServerWithRegFileTypeLib
{
    importlib("stdole32.tlb");
    // Component code
    [
        uuid(9AEA1E50-D8C7-4353-9AA7-B91CB174D9AC),
        helpstring("My Automation Component Class")
    ]
    coclass MyMath
    {
        [default] interface IMyMath;
    };
};
